### ISSUE TITLE
A

### ISSUE THREAD

**Issue by LolomingCode** [Los-pibes-de-la-tec/Proyecto_EEE501#1]
The name of the repo Is wrong because one of the members did not go to the technique, Fix it quickly, or te re cago a piñas gil 
Ty.

**Comment by retaLazyCodes** [comment]
"The technique" 🤣

**Comment by retaLazyCodes** [comment]
> The name of the repo Is wrong because one of the members did not go to the technique, Fix it quickly, or te re cago a piñas gil Ty.

"The technique" 🤣

**Comment by retaLazyCodes** [comment]
@LolomingCode Flaco mepa que estás un poco alterado, así que te voy a tener que cerrar la issue.
Gracias por reportar el problema, y buenas tardes.
